services:
  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: cube_chat
      POSTGRES_PASSWORD: cube_chat
      POSTGRES_DB: cube_chat
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready -d cube_chat -U cube_chat" ]
      interval: 1s
      timeout: 3s
      retries: 30
  redis:
    image: redis:7-alpine
    volumes:
      - ./volumes/redis/data:/data
    ports:
      - "6379:6379"
    command: redis-server --requirepass cube_chat
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
